version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      - ./.data/redis:/data
