version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
#  redis:
#    image: redis:5.0.5
#    env_file:
#      - .env
#    ports:
#      - 6379:6379
#    volumes:
#      - ./.data/redis:/data
#  elasticsearch:
#    image: elasticsearch:6.5.4
#    env_file:
#      - .env/vars
#    ports:
#      - 9200:9200
#      - 9300:9300
#    volumes:
#      - ./.data/elasticsearch:/usr/share/elasticsearch/data
