# Generated by Django 2.2.19 on 2021-04-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_restoring_password',
            field=models.BooleanField(default=False, help_text='Designates that this user should confirm email after password reset . ', verbose_name='restoring_password'),
        ),
    ]
